# Dependencies
# ---------------------------------------------------------------------------

markdown:         rdiscount
highlighter:      true

# Permalinks
# ---------------------------------------------------------------------------

permalink:        pretty

# Server
# ---------------------------------------------------------------------------

source:           app/
destination:      _gh_pages
port:             4002
baseurl:          http://pongstr.github.io/rolling-into-deep/
url:              http://pongstr.github.io/rolling-into-deep/
encoding:         UTF-8


# Site Information
# ---------------------------------------------------------------------------

title:        "RollingIntoDeep"
tagline:      "a collection of components and complex blocks which can easily be integrated into almost any design."
version:      "0.1.0"

author:      "Pongstr"
description: "a collection of components and complex blocks which can easily be integrated into almost any design."
keywords:    ""